"""Fix null constraints

Revision ID: 22579e8dba13
Revises: 1486226bf75d
Create Date: 2021-02-22 17:32:17.673610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22579e8dba13'
down_revision = '1486226bf75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(length=50), nullable=False))
    op.create_unique_constraint('events_name_key', 'events', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_name_key', 'events', type_='unique')
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
